name: abc_sbpu_project
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  auto_route: ^9.2.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  excel:
    git:
      url: https://github.com/YaroCabbage/excel.git
      ref: issue_45
      version: 4.0.6

  cupertino_icons: ^1.0.6
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

dependency_overrides:
  path: 1.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/

flutter_intl:
  enabled: true
  main_locale: ru